package br.org.cac.repositories;

import java.util.Date;
import java.util.List;

import javax.validation.Valid;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import br.org.cac.models.Campanha;
import br.org.cac.models.Doacao;
import br.org.cac.models.Item;
import br.org.cac.models.ItemDoacao;

/**
 * Generated by Spring Data Generator on 16/03/2019
 */
@Repository
public interface ItemDoacaoRepository extends
		JpaRepository<ItemDoacao, Integer>,
		JpaSpecificationExecutor<ItemDoacao> {

	List<ItemDoacao> findAllByDoacao(Doacao doacao);

	List<ItemDoacao> findAllByCampanha(Campanha campanha);

	List<ItemDoacao> findAllByItem(Item item);

	@Query("SELECT id FROM ItemDoacao id WHERE id.doacao = :doacao and id.item = :item")
	List<ItemDoacao> findAllByDoacaoByItem(@Param("doacao") Doacao doacao,
			@Param("item") Item item);

	@Query("SELECT id FROM ItemDoacao id WHERE id.doacao = :doacao and id.campanha = :campanha")
	List<ItemDoacao> findAllByDoacaoByCampanha(@Param("doacao") Doacao doacao,
			@Param("campanha") Campanha campanha);
	
	@Query("SELECT id FROM ItemDoacao id WHERE id.doacao = :doacao and id.campanha = :campanha and id.item = :item")
	List<ItemDoacao> findAllByDoacaoByCampanhaByItem(@Param("doacao") Doacao doacao,
			@Param("campanha") Campanha campanha, @Param("item") Item item);

	@Transactional
	@Modifying
	@Query("Update ItemDoacao id set id.campanha = :campanha where id.doacao=:doacao")
	void atualizarCampanha(@Param("doacao") Doacao doacao,
			@Param("campanha") Campanha campanha);

	@Transactional
	@Modifying
	@Query("Update ItemDoacao id set id.campanha = :campanha where id.doacao=:doacao and id.item = :item")
	void atualizarCampanhaItem(@Param("doacao") Doacao doacao,
			@Param("campanha") Campanha campanha, @Param("item") Item item);

	@Query("SELECT id FROM ItemDoacao id WHERE id.doacao.cadastro BETWEEN :dataInicial AND :dataFinal")
	List<ItemDoacao> findAllByDataInicioByDataFim(@Param("dataInicial") Date dataInicial,
			@Param("dataFinal") Date dataFinal);
	
	

	// List<ItemDoacao> findAllByCampanhaByDocao(Campanha campanha, Doacao
	// doacao);

}
